// bintoc.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

#include<stdio.h>   
#include<fcntl.h>   
#include<io.h>   


//bintoc 数组名 输入文件名 > 输出文件名

int main(int argc, char * argv[])   
{   
  const int CLINE = 16;   
  FILE *pin = stdin;   
  char *array_name = NULL;   
  int c = 0, lastc=EOF;   
  int ccount = 0;   

  argv++;argc--; //no need program name   
  if (argc ) 
  {   
    array_name = argv[0];   
    argv++;argc--;   
  } 
  else 
  {   
    fprintf(stderr, "Array Name Must Be Supplied.\n", argv[1]);   
    return -1;   
  }   
  if (argc) 
  {   
    pin = fopen(argv[0], "rb");   
    if (pin == NULL) 
	{   
      fprintf(stderr, "Error Open File %s.\n", argv[1]);   
      return -1;  
    }   
  } 
  else 
  {   
    _setmode(_fileno(stdin), O_BINARY);   
  }   
  printf("/*** Generated by bintoc. Don't edit! ***/\nunsigned char %s[] =\n{", array_name);   
     
  for(c = fgetc(pin); c!=EOF; c = fgetc(pin)) 
  {   
    if (lastc!=EOF)   
      printf("0x%02X,", lastc);   
    lastc = c;   
    if (ccount++ % CLINE == 0)   
      printf("\n");   
  }   
  printf("0x%02X", lastc);   
  printf("\n};\n");   

  return 0;
}  

