//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MagicBurning.rc
//
#define ID_BTN_NEXT                     3
#define ID_BTN_BACK                     4
#define ID_BTN_CLOSE                    6
#define IDD_MAGICBURNING_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     129
#define IDB_BITMAP2                     130
#define ID_FINDPR_COMBO_PRLIST          133
#define IDS_FINDPR_PROGRESSCTRL         134
#define ID_FINDPR_PROGRESSCTRL          134
#define IDD_GETPRO                      134
#define IDD_GETMCU                      135
#define IDD_SETCFG                      136
#define IDD_GETSTS                      137
#define IDD_GETCOM                      138
#define IDI_ICON1                       139
#define IDI_ICON_LEDOFF                 141
#define IDI_ICON_LEDON                  142
#define IDD_GETAUTH                     143
#define IDD_SETAUTH                     144
#define IDC_STATIC_H                    1001
#define IDC_STATIC_V                    1002
#define ID_BTN_CANCEL                   1003
#define IDC_STATIC_TEXT                 1007
#define IDC_TAB1                        1008
#define IDC_TAB_PAGECTRL                1008
#define IDC_LIST_PAGE                   1010
#define IDC_COMBO1                      1011
#define IDC_EDIT1                       1012
#define IDC_STATIC_TARGET               1013
#define IDC_EDIT_UL                     1013
#define IDC_EDIT_MCUPID                 1013
#define IDC_STATIC_PID                  1014
#define IDC_EDIT_SEC                    1014
#define IDC_EDIT2                       1015
#define IDC_EDIT_CFL                    1015
#define IDC_STATIC_FM                   1016
#define IDC_STATIC_MCUPID               1016
#define IDC_EDIT_CFBK                   1016
#define IDC_STATIC_NPT                  1017
#define IDC_EDIT_MCUVER                 1017
#define IDC_STATIC_PT                   1018
#define IDC_EDIT_MCUVER2                1018
#define IDC_EDIT_MCUFLB                 1018
#define IDC_STATIC_LE                   1019
#define IDC_STATIC_PRO                  1020
#define IDC_STATIC_MCU                  1021
#define IDC_STATIC_MCUS                 1022
#define IDC_COMBO_BR                    1023
#define IDC_COMBO_DB                    1024
#define IDC_STATIC_CM                   1025
#define IDC_STATIC_DB                   1026
#define IDC_STATIC_TO                   1027
#define IDC_COMBO_BR2                   1028
#define IDC_COMBO_TO                    1028
#define IDC_PROGRESS1                   1029
#define IDC_PROGRESS_OP                 1029
#define IDC_STATIC_AUTH                 1029
#define IDC_PROGRESS_GLOBAL             1029
#define IDC_STATIC_BR2                  1030
#define IDC_RADIO_ERASE                 1030
#define IDC_COMBO_BR3                   1031
#define IDC_STATIC_ERASE                1031
#define IDC_RADIO_ERASE_ALL             1032
#define IDC_STATIC_MCU2                 1032
#define IDC_RADIO_ERASE_ALL2            1033
#define IDC_RADIO_OFFLINE               1033
#define IDC_RADIO_ERASE_SEL             1033
#define IDC_BUTTON_ERASE                1034
#define IDC_RADIO_ONLINE                1034
#define IDC_RADIO_DL                    1035
#define IDC_RADIO_AUTHPASS              1035
#define IDC_STATIC_DL                   1036
#define IDC_RADIO_REMOVEPASS            1036
#define IDC_BUTTON_DL                   1037
#define IDC_STATIC_DL_SUB               1038
#define IDC_RADIO_DL_ENP                1039
#define IDC_RADIO_DL_NE                 1040
#define IDC_RADIO_DL_GE                 1041
#define IDC_STATIC_DL_SUB2              1042
#define IDC_COMBO_ADR                   1043
#define IDC_CHECK_JUSER                 1044
#define IDC_CHECK_RFF                   1045
#define IDC_CHECK_VAD                   1046
#define IDC_RADIO_DL2                   1047
#define IDC_RADIO_UL                    1047
#define IDC_STATIC_UL                   1048
#define IDC_BUTTON_UL                   1049
#define IDC_STATIC_TARGET_T             1049
#define IDC_RADIO_SEC                   1050
#define IDC_STATIC_TARGET_C             1050
#define IDC_STATIC_PROCOM               1050
#define IDC_RADIO_RESTORE               1050
#define IDC_STATIC_UL2                  1051
#define IDC_STATIC_MAP_T                1051
#define IDC_STATIC_PROCOM2              1051
#define IDC_STATIC_MCUSEC               1051
#define IDC_STATIC_MCUCOM               1051
#define IDC_RADIO_SEC_REP               1052
#define IDC_STATIC_MAP_C                1052
#define IDC_RADIO_SEC_EN                1053
#define IDC_STATIC_OP_T                 1053
#define IDC_BUTTON_RP                   1053
#define IDC_RADIO_SEC_DE                1054
#define IDC_STATIC_OP_C                 1054
#define IDC_COMBO_PRO                   1054
#define IDC_RADIO_CPD                   1054
#define IDC_STATIC_FILE_T               1055
#define IDC_COMBO_MCUS                  1055
#define IDC_STATIC_PROPID               1055
#define IDC_RADIO_CFL                   1055
#define IDC_STATIC_FILE_C               1056
#define IDC_STATIC_PROVER               1056
#define IDC_STATIC_CFL                  1056
#define IDC_STATIC_FS_T                 1057
#define IDC_EDIT_PROPID                 1057
#define IDC_RADIO_CFLD                  1057
#define IDC_STATIC_FS_C                 1058
#define IDC_EDIT_PROVER                 1058
#define IDC_RADIO_CFBK                  1058
#define IDC_STATIC_STS_T                1059
#define IDC_STATIC_MCUVER               1059
#define IDC_STATIC_CFBK                 1059
#define IDC_STATIC_STS_C                1060
#define IDC_EDIT_DL                     1060
#define IDC_RADIO_CFBKD                 1060
#define IDC_STATIC_MCUFLB               1060
#define IDC_STATIC_TIME_T               1061
#define IDC_PROGRESS_CON                1061
#define IDC_PROGRESS_COM                1061
#define IDC_STATIC_STS_C2               1062
#define IDC_STATIC_TIME_C               1062
#define IDC_RADIO_CFBKD2                1062
#define IDC_RADIO_CFBKNO                1062
#define IDC_STATIC_PROCOMTXT            1063
#define IDC_STATIC_MCUCOMTXT            1064
#define IDC_STATIC_WARNING              1064
#define IDC_STATIC_CAUTION              1064
#define IDC_EDIT_AUTHPASS               1065
#define IDC_BUTTON_SEC                  1066
#define IDC_STATIC_LEFTTIMES            1067
#define IDC_EDIT_ADR                    1069
#define IDC_STATIC_SH2                  1070
#define IDC_STATIC_SH1                  1071
#define IDC_STATIC_CFLH                 1071
#define IDC_STATIC_TRYTIMES             1072
#define IDC_COMBO_TRYTIMES              1073
#define IDC_STATIC_CFBKH                1073
#define IDC_EDIT_FILE_C                 1074
#define IDC_RADIO_PASSWR                1075
#define IDC_RADIO_PASSNOWR              1076
#define IDC_STATIC_PASS_1               1077
#define IDC_RADIO_CP                    1078
#define IDC_STATIC_CP                   1079
#define IDC_EDIT_CP                     1080
#define IDC_STATIC_CPH                  1081
#define IDC_STATIC_CPTT                 1082
#define IDC_EDIT_CPTT                   1083
#define IDC_STATIC_CPTT1                1084

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
