#ifndef __SI6600_H
#define __SI6600_H

// MCU INFO DEFINE

#define PWD_FLAG_OFFSET (0x400)
#define PWD_FLAG_LEN (4)
#define PWD_MAX_AUTH_OFFSET (PWD_FLAG_OFFSET+PWD_FLAG_LEN)
#define	PWD_MAX_AUTH_LEN (4)
#define PWD_INFO_OFFSET (PWD_MAX_AUTH_OFFSET+PWD_MAX_AUTH_LEN)
#define PWD_LEN (16)
#define FLASH_LOCK_BIT_OFFSET (PWD_INFO_OFFSET+PWD_LEN)
#define FLASH_LOCK_BIT_LEN (32)
#define FLASH_BUS_KEY_OFFSET (FLASH_LOCK_BIT_OFFSET+FLASH_LOCK_BIT_LEN)
#define FLASH_BUS_KEY_LEN (16)
#define FLASH_BUS_KEY_EN_OFFSET (FLASH_BUS_KEY_OFFSET+FLASH_BUS_KEY_LEN)
#define FLASH_BUS_KEY_EN_LEN (4)

#define ALL_PWD_LEN (PWD_FLAG_LEN+PWD_MAX_AUTH_LEN+PWD_LEN+FLASH_LOCK_BIT_LEN+FLASH_BUS_KEY_LEN+FLASH_BUS_KEY_EN_LEN)

#define CUR_PWD_OFFSET (0x7f0)
#define CUR_PWD_LEN (4)

#define MCU_PID_OFFSET (0x3E4)
#define MCU_PID_LEN (4)
#define MCU_REVISION_OFFSET (0x3E4)
#define MCU_REVISION_LEN (4)
#define MCU_CHIP_ID_OFFSET (0x3e8)
#define MCU_CHIP_ID_LEN (8)

//page erase
#define INFO_PAGE_1_READDR (0x400)

#endif
