#ifndef __REG_H__
#define __REG_H__


#define UART_1_BASEADDR       (0x40000000)

    #define UART_1_RBR          *((volatile unsigned char *)(UART_1_BASEADDR+0x00))
		#define UART_1_THR          *((volatile unsigned char *)(UART_1_BASEADDR+0x00))
		#define UART_1_DLL          *((volatile unsigned char *)(UART_1_BASEADDR+0x00))
		#define UART_1_DLH          *((volatile unsigned char *)(UART_1_BASEADDR+0x04))
		#define UART_1_IER          *((volatile unsigned char *)(UART_1_BASEADDR+0x04))
		#define UART_1_IIR          *((volatile unsigned char *)(UART_1_BASEADDR+0x08))
		#define UART_1_FCR          *((volatile unsigned char *)(UART_1_BASEADDR+0x08))
		#define UART_1_LCR          *((volatile unsigned char *)(UART_1_BASEADDR+0x0c))			
		#define UART_1_LSR          *((volatile unsigned char *)(UART_1_BASEADDR+0x14))	
			
#define UART_2_BASEADDR       (0x40000400)

    #define UART_2_RBR          *((volatile unsigned char *)(UART_2_BASEADDR+0x00))
		#define UART_2_THR          *((volatile unsigned char *)(UART_2_BASEADDR+0x00))
		#define UART_2_DLL          *((volatile unsigned char *)(UART_2_BASEADDR+0x00))
		#define UART_2_DLH          *((volatile unsigned char *)(UART_2_BASEADDR+0x04))
		#define UART_2_IER          *((volatile unsigned char *)(UART_2_BASEADDR+0x04))
		#define UART_2_IIR          *((volatile unsigned char *)(UART_2_BASEADDR+0x08))
		#define UART_2_FCR          *((volatile unsigned char *)(UART_2_BASEADDR+0x08))
		#define UART_2_LCR          *((volatile unsigned char *)(UART_2_BASEADDR+0x0c))			
		#define UART_2_LSR          *((volatile unsigned char *)(UART_2_BASEADDR+0x14))	

#define UART_3_BASEADDR       (0x40000800)

    #define UART_3_RBR          *((volatile unsigned char *)(UART_3_BASEADDR+0x00))
		#define UART_3_THR          *((volatile unsigned char *)(UART_3_BASEADDR+0x00))
		#define UART_3_DLL          *((volatile unsigned char *)(UART_3_BASEADDR+0x00))
		#define UART_3_DLH          *((volatile unsigned char *)(UART_3_BASEADDR+0x04))
		#define UART_3_IER          *((volatile unsigned char *)(UART_3_BASEADDR+0x04))
		#define UART_3_IIR          *((volatile unsigned char *)(UART_3_BASEADDR+0x08))
		#define UART_3_FCR          *((volatile unsigned char *)(UART_3_BASEADDR+0x08))
		#define UART_3_LCR          *((volatile unsigned char *)(UART_3_BASEADDR+0x0c))			
		#define UART_3_LSR          *((volatile unsigned char *)(UART_3_BASEADDR+0x14))	
			
#define I2C_1_BASEADDR       (0x40000c00)
		#define I2C_1_CON           *((volatile unsigned int *)(I2C_1_BASEADDR+0x00))
		#define I2C_1_TAR           *((volatile unsigned int *)(I2C_1_BASEADDR+0x04))
		#define I2C_1_SAR           *((volatile unsigned int *)(I2C_1_BASEADDR+0x08))
		#define I2C_1_HS_MADDR      *((volatile unsigned int *)(I2C_1_BASEADDR+0x0c))
		#define I2C_1_DATA_CMD      *((volatile unsigned int *)(I2C_1_BASEADDR+0x10))
		#define I2C_1_SS_SCL_HCNT   *((volatile unsigned int *)(I2C_1_BASEADDR+0x14))
		#define I2C_1_SS_SCL_LCNT   *((volatile unsigned int *)(I2C_1_BASEADDR+0x18)) 
		#define I2C_1_FS_SCL_HCNT   *((volatile unsigned int *)(I2C_1_BASEADDR+0x1c))
		#define I2C_1_FS_SCL_LCNT   *((volatile unsigned int *)(I2C_1_BASEADDR+0x20))
		#define I2C_1_HS_SCL_HCNT   *((volatile unsigned int *)(I2C_1_BASEADDR+0x24))
		#define I2C_1_HS_SCL_LCNT   *((volatile unsigned int *)(I2C_1_BASEADDR+0x28))
		#define I2C_1_INTR_STAT     *((volatile unsigned int *)(I2C_1_BASEADDR+0x2c))
		#define I2C_1_INTR_MASK     *((volatile unsigned int *)(I2C_1_BASEADDR+0x30))
		#define I2C_1_RAW_INTR_STAT *((volatile unsigned int *)(I2C_1_BASEADDR+0x34))
		#define I2C_1_RX_TL         *((volatile unsigned int *)(I2C_1_BASEADDR+0x38))
		#define I2C_1_TX_TL         *((volatile unsigned int *)(I2C_1_BASEADDR+0x3c))
		#define I2C_1_CLR_INTR      *((volatile unsigned int *)(I2C_1_BASEADDR+0x40))
		#define I2C_1_ENABLE        *((volatile unsigned int *)(I2C_1_BASEADDR+0x6c))
		#define I2C_1_STATUS        *((volatile unsigned int *)(I2C_1_BASEADDR+0x70))
		#define I2C_1_TXFLR         *((volatile unsigned int *)(I2C_1_BASEADDR+0x74))
		#define I2C_1_RXFLR         *((volatile unsigned int *)(I2C_1_BASEADDR+0x78))
		#define I2C_1_SDA_HOLD      *((volatile unsigned int *)(I2C_1_BASEADDR+0x7c))
		#define I2C_1_TX_ABRT_SOURCE *((volatile unsigned int *)(I2C_1_BASEADDR+0x80))
		#define I2C_1_DMA_CR        *((volatile unsigned int *)(I2C_1_BASEADDR+0x88))
		#define I2C_1_DMA_TDLR      *((volatile unsigned int *)(I2C_1_BASEADDR+0x8c))
		#define I2C_1_DMA_RDLR      *((volatile unsigned int *)(I2C_1_BASEADDR+0x90))
		
#define SSIM_1_BASEADDR      (0x40001000)
		#define SSIM_1_CTRLR0       *((volatile unsigned int *)(SSIM_1_BASEADDR+0x00))
		#define SSIM_1_CTRLR1       *((volatile unsigned int *)(SSIM_1_BASEADDR+0x04))
		#define SSIM_1_SSIENR       *((volatile unsigned int *)(SSIM_1_BASEADDR+0x08))
		#define SSIM_1_SER          *((volatile unsigned int *)(SSIM_1_BASEADDR+0x10))
		#define SSIM_1_BAUDR        *((volatile unsigned int *)(SSIM_1_BASEADDR+0x14))
		#define SSIM_1_TXFTLR       *((volatile unsigned int *)(SSIM_1_BASEADDR+0x18))
		#define SSIM_1_RXFTLR       *((volatile unsigned int *)(SSIM_1_BASEADDR+0x1c))
		#define SSIM_1_TXFLR        *((volatile unsigned int *)(SSIM_1_BASEADDR+0x20))
		#define SSIM_1_RXFLR        *((volatile unsigned int *)(SSIM_1_BASEADDR+0x24))
		#define SSIM_1_SR           *((volatile unsigned int *)(SSIM_1_BASEADDR+0x28))
		#define SSIM_1_IMR          *((volatile unsigned int *)(SSIM_1_BASEADDR+0x2c))
		#define SSIM_1_ISR          *((volatile unsigned int *)(SSIM_1_BASEADDR+0x30))
		#define SSIM_1_RISR         *((volatile unsigned int *)(SSIM_1_BASEADDR+0x34))
		#define SSIM_1_ICR          *((volatile unsigned int *)(SSIM_1_BASEADDR+0x48))
		#define SSIM_1_DMACR        *((volatile unsigned int *)(SSIM_1_BASEADDR+0x4c))
		#define SSIM_1_DMATDLR      *((volatile unsigned int *)(SSIM_1_BASEADDR+0x50))
		#define SSIM_1_DMARDLR      *((volatile unsigned int *)(SSIM_1_BASEADDR+0x54))
		#define SSIM_1_DR           *((volatile unsigned int *)(SSIM_1_BASEADDR+0x60))		
		
#define SSIM_2_BASEADDR      (0x40001400)
		#define SSIM_2_CTRLR0       *((volatile unsigned int *)(SSIM_2_BASEADDR+0x00))
		#define SSIM_2_CTRLR1       *((volatile unsigned int *)(SSIM_2_BASEADDR+0x04))
		#define SSIM_2_SSIENR       *((volatile unsigned int *)(SSIM_2_BASEADDR+0x08))
		#define SSIM_2_SER          *((volatile unsigned int *)(SSIM_2_BASEADDR+0x10))
		#define SSIM_2_BAUDR        *((volatile unsigned int *)(SSIM_2_BASEADDR+0x14))
		#define SSIM_2_TXFTLR       *((volatile unsigned int *)(SSIM_2_BASEADDR+0x18))
		#define SSIM_2_RXFTLR       *((volatile unsigned int *)(SSIM_2_BASEADDR+0x1c))
		#define SSIM_2_TXFLR        *((volatile unsigned int *)(SSIM_2_BASEADDR+0x20))
		#define SSIM_2_RXFLR        *((volatile unsigned int *)(SSIM_2_BASEADDR+0x24))
		#define SSIM_2_SR           *((volatile unsigned int *)(SSIM_2_BASEADDR+0x28))
		#define SSIM_2_IMR          *((volatile unsigned int *)(SSIM_2_BASEADDR+0x2c))
		#define SSIM_2_ISR          *((volatile unsigned int *)(SSIM_2_BASEADDR+0x30))
		#define SSIM_2_RISR         *((volatile unsigned int *)(SSIM_2_BASEADDR+0x34))
		#define SSIM_2_ICR          *((volatile unsigned int *)(SSIM_2_BASEADDR+0x48))
		#define SSIM_2_DMACR        *((volatile unsigned int *)(SSIM_2_BASEADDR+0x4c))
		#define SSIM_2_DMATDLR      *((volatile unsigned int *)(SSIM_2_BASEADDR+0x50))
		#define SSIM_2_DMARDLR      *((volatile unsigned int *)(SSIM_2_BASEADDR+0x54))
		#define SSIM_2_DR           *((volatile unsigned int *)(SSIM_2_BASEADDR+0x60))	
		
#define SSIS_1_BASEADDR      (0x40001800)
		#define SSIS_1_CTRLR0       *((volatile unsigned int *)(SSIS_1_BASEADDR+0x00))
		#define SSIS_1_CTRLR1       *((volatile unsigned int *)(SSIS_1_BASEADDR+0x04))
		#define SSIS_1_SSIENR       *((volatile unsigned int *)(SSIS_1_BASEADDR+0x08))
		#define SSIS_1_SER          *((volatile unsigned int *)(SSIS_1_BASEADDR+0x10))
		#define SSIS_1_BAUDR        *((volatile unsigned int *)(SSIS_1_BASEADDR+0x14))
		#define SSIS_1_TXFTLR       *((volatile unsigned int *)(SSIS_1_BASEADDR+0x18))
		#define SSIS_1_RXFTLR       *((volatile unsigned int *)(SSIS_1_BASEADDR+0x1c))
		#define SSIS_1_TXFLR        *((volatile unsigned int *)(SSIS_1_BASEADDR+0x20))
		#define SSIS_1_RXFLR        *((volatile unsigned int *)(SSIS_1_BASEADDR+0x24))
		#define SSIS_1_SR           *((volatile unsigned int *)(SSIS_1_BASEADDR+0x28))
		#define SSIS_1_IMR          *((volatile unsigned int *)(SSIS_1_BASEADDR+0x2c))
		#define SSIS_1_ISR          *((volatile unsigned int *)(SSIS_1_BASEADDR+0x30))
		#define SSIS_1_RISR         *((volatile unsigned int *)(SSIS_1_BASEADDR+0x34))
		#define SSIS_1_ICR          *((volatile unsigned int *)(SSIS_1_BASEADDR+0x48))
		#define SSIS_1_DMACR        *((volatile unsigned int *)(SSIS_1_BASEADDR+0x4c))
		#define SSIS_1_DMATDLR      *((volatile unsigned int *)(SSIS_1_BASEADDR+0x50))
		#define SSIS_1_DMARDLR      *((volatile unsigned int *)(SSIS_1_BASEADDR+0x54))
		#define SSIS_1_DR           *((volatile unsigned int *)(SSIS_1_BASEADDR+0x60))	
		
#define SSIS_2_BASEADDR      (0x40001c00)
		#define SSIS_2_CTRLR0       *((volatile unsigned int *)(SSIS_2_BASEADDR+0x00))
		#define SSIS_2_CTRLR1       *((volatile unsigned int *)(SSIS_2_BASEADDR+0x04))
		#define SSIS_2_SSIENR       *((volatile unsigned int *)(SSIS_2_BASEADDR+0x08))
		#define SSIS_2_SER          *((volatile unsigned int *)(SSIS_2_BASEADDR+0x10))
		#define SSIS_2_BAUDR        *((volatile unsigned int *)(SSIS_2_BASEADDR+0x14))
		#define SSIS_2_TXFTLR       *((volatile unsigned int *)(SSIS_2_BASEADDR+0x18))
		#define SSIS_2_RXFTLR       *((volatile unsigned int *)(SSIS_2_BASEADDR+0x1c))
		#define SSIS_2_TXFLR        *((volatile unsigned int *)(SSIS_2_BASEADDR+0x20))
		#define SSIS_2_RXFLR        *((volatile unsigned int *)(SSIS_2_BASEADDR+0x24))
		#define SSIS_2_SR           *((volatile unsigned int *)(SSIS_2_BASEADDR+0x28))
		#define SSIS_2_IMR          *((volatile unsigned int *)(SSIS_2_BASEADDR+0x2c))
		#define SSIS_2_ISR          *((volatile unsigned int *)(SSIS_2_BASEADDR+0x30))
		#define SSIS_2_RISR         *((volatile unsigned int *)(SSIS_2_BASEADDR+0x34))
		#define SSIS_2_ICR          *((volatile unsigned int *)(SSIS_2_BASEADDR+0x48))
		#define SSIS_2_DMACR        *((volatile unsigned int *)(SSIS_2_BASEADDR+0x4c))
		#define SSIS_2_DMATDLR      *((volatile unsigned int *)(SSIS_2_BASEADDR+0x50))
		#define SSIS_2_DMARDLR      *((volatile unsigned int *)(SSIS_2_BASEADDR+0x54))
		#define SSIS_2_DR           *((volatile unsigned int *)(SSIS_2_BASEADDR+0x60))
		
#define HS_MUX_BASEADDR      (0x40002000)
		#define HS0_CFG            *((volatile unsigned int  *)(HS_MUX_BASEADDR+0x00))
		#define HS1_CFG            *((volatile unsigned int  *)(HS_MUX_BASEADDR+0x04))
		#define HS2_CFG            *((volatile unsigned int  *)(HS_MUX_BASEADDR+0x08))
		#define HS3_CFG            *((volatile unsigned int  *)(HS_MUX_BASEADDR+0x0c))
			
#define PASSWORD_BASEADDR    (0x40002400)			
		#define SPI_PASSWORD0      *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x00))
    #define SPI_PASSWORD1      *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x04))
    #define SPI_PASSWORD2      *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x08))
    #define SPI_PASSWORD3      *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x0C))
    #define SPI_PASSWORD4      *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x10))
    #define SPI_PASSWORD5      *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x14))
    #define SPI_PASSWORD6      *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x18))
    #define SPI_PASSWORD7      *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x1C))
    #define PASSWORD0          *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x40))
    #define PASSWORD1          *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x44))
    #define PASSWORD2          *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x48))
    #define PASSWORD3          *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x4C))
    #define PASSWORD4          *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x50))
    #define PASSWORD5          *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x54))
    #define PASSWORD6          *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x58))
    #define PASSWORD7          *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x5C))                   
    #define BUSENC0            *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x60))
    #define BUSENC1            *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x64))
    #define BUSENC2            *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x68))
    #define BUSENC3            *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x6C))
    #define BUSENC4            *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x70))
    #define BUSENC5            *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x74))
    #define BUSENC6            *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x78))
    #define BUSENC7            *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x7C))
    #define CALIBATRION0       *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x80))
    #define CALIBATRION1       *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x84))
    #define CALIBATRION2       *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x88))
    #define CALIBATRION3       *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x8C))
    #define CALIBATRION4       *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x90))
    #define CALIBATRION5       *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x94))
    #define CALIBATRION6       *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x98))
    #define CALIBATRION7       *((volatile unsigned int  *)(PASSWORD_BASEADDR+0x9C))

		
#define SCI7816_BASEADDR     (0x40002800)
		#define SCI_CON            *((volatile unsigned int  *)(SCI7816_BASEADDR+0x00))
		#define SCI_MODE           *((volatile unsigned int  *)(SCI7816_BASEADDR+0x04))
		#define SCI_STATUS         *((volatile unsigned int  *)(SCI7816_BASEADDR+0x08))
		#define SCI_FIFO_STATUS    *((volatile unsigned int  *)(SCI7816_BASEADDR+0x0c))
		#define SCI_FIFO_DEPTH     *((volatile unsigned int  *)(SCI7816_BASEADDR+0x10))
		#define SCI_DATA           *((volatile unsigned int  *)(SCI7816_BASEADDR+0x14))
		#define EDC_DATA           *((volatile unsigned int  *)(SCI7816_BASEADDR+0x18))
		#define SCI_SBDR           *((volatile unsigned int  *)(SCI7816_BASEADDR+0x1c))
		#define SCI_ETU_CNT        *((volatile unsigned int  *)(SCI7816_BASEADDR+0x20))
		#define SCI_INT_CLK_RST    *((volatile unsigned int  *)(SCI7816_BASEADDR+0x24))
		
#define TIMER_BASEADDR        (0x40002c00)
		#define TIMER1_LOAD_COUNT  *((volatile unsigned int  *)(TIMER_BASEADDR+0x00))
		#define TIMER1_CURVAL      *((volatile unsigned char *)(TIMER_BASEADDR+0x04))
		#define TIMER1_CTRL        *((volatile unsigned char *)(TIMER_BASEADDR+0x08))
		#define TIMER1_EOI         *((volatile unsigned int  *)(TIMER_BASEADDR+0x0c))	
    #define TIMER1_LOAD_COUNT2 *((volatile unsigned int  *)(TIMER_BASEADDR+0xb0))			
			
		#define TIMER2_LOAD_COUNT  *((volatile unsigned int  *)(TIMER_BASEADDR+0x14))
		#define TIMER2_CURVAL      *((volatile unsigned char *)(TIMER_BASEADDR+0x18))
		#define TIMER2_CTRL        *((volatile unsigned char *)(TIMER_BASEADDR+0x1c))
		#define TIMER2_EOI         *((volatile unsigned int  *)(TIMER_BASEADDR+0x20))	
		#define TIMER2_LOAD_COUNT2 *((volatile unsigned int  *)(TIMER_BASEADDR+0xb4))
			
		#define TIMER3_LOAD_COUNT  *((volatile unsigned int  *)(TIMER_BASEADDR+0x28))
		#define TIMER3_CURVAL      *((volatile unsigned char *)(TIMER_BASEADDR+0x2c))
		#define TIMER3_CTRL        *((volatile unsigned char *)(TIMER_BASEADDR+0x30))
		#define TIMER3_EOI         *((volatile unsigned int  *)(TIMER_BASEADDR+0x34))	
    #define TIMER3_LOAD_COUNT2 *((volatile unsigned int  *)(TIMER_BASEADDR+0xb8))			
			
		#define TIMER4_LOAD_COUNT  *((volatile unsigned int  *)(TIMER_BASEADDR+0x3c))
		#define TIMER4_CURVAL      *((volatile unsigned char *)(TIMER_BASEADDR+0x40))
		#define TIMER4_CTRL        *((volatile unsigned char *)(TIMER_BASEADDR+0x44))
		#define TIMER4_EOI         *((volatile unsigned int  *)(TIMER_BASEADDR+0x48))
		#define TIMER4_LOAD_COUNT2 *((volatile unsigned int  *)(TIMER_BASEADDR+0xbc))
			
		#define TIMERS_INT_STAT    *((volatile unsigned int  *)(TIMER_BASEADDR+0xa0))
		#define TIMERS_EOI         *((volatile unsigned int  *)(TIMER_BASEADDR+0xa4))
			
		#define TIMERS_GATE        *((volatile unsigned int  *)(TIMER_BASEADDR+0xd0))		
		
#define RNG_BASEADDR          (0x40003000)
		#define RNGCTRL            *((volatile unsigned int  *)(RNG_BASEADDR+0x00))
		#define RNGMODE            *((volatile unsigned int  *)(RNG_BASEADDR+0x04))
		#define RNGSEQ             *((volatile unsigned int  *)(RNG_BASEADDR+0x08))
		#define RNGDATA0           *((volatile unsigned int  *)(RNG_BASEADDR+0x0c))
	  #define RNGDATA0_0           *((volatile unsigned char  *)(RNG_BASEADDR+0x0c))
		#define RNGDATA0_1           *((volatile unsigned char  *)(RNG_BASEADDR+0x0d))
		#define RNGDATA0_2           *((volatile unsigned char  *)(RNG_BASEADDR+0x0e))
		#define RNGDATA0_3           *((volatile unsigned char  *)(RNG_BASEADDR+0x0f))
		#define RNGDATA1           *((volatile unsigned int  *)(RNG_BASEADDR+0x10))
		#define RNGDATA1_0           *((volatile unsigned char  *)(RNG_BASEADDR+0x10))
		#define RNGDATA1_1           *((volatile unsigned char  *)(RNG_BASEADDR+0x11))
		#define RNGDATA1_2           *((volatile unsigned char  *)(RNG_BASEADDR+0x12))
		#define RNGDATA1_3           *((volatile unsigned char  *)(RNG_BASEADDR+0x13))
		
#define LCD_BASEADDR          (0x40003400)
	  #define LCDRAM0L            *((volatile unsigned int *)(LCD_BASEADDR+0x00))
    #define LCDRAM1L            *((volatile unsigned int *)(LCD_BASEADDR+0x04))
    #define LCDRAM2L            *((volatile unsigned int *)(LCD_BASEADDR+0x08))
    #define LCDRAM3L            *((volatile unsigned int *)(LCD_BASEADDR+0x0C))
    #define LCDRAM4L            *((volatile unsigned int *)(LCD_BASEADDR+0x10))
    #define LCDRAM5L            *((volatile unsigned int *)(LCD_BASEADDR+0x14))
    #define LCDRAM6L            *((volatile unsigned int *)(LCD_BASEADDR+0x18))
    #define LCDRAM7L            *((volatile unsigned int *)(LCD_BASEADDR+0x1C))
    #define LCDRAM0H            *((volatile unsigned int *)(LCD_BASEADDR+0x20))
    #define LCDRAM1H            *((volatile unsigned int *)(LCD_BASEADDR+0x24))
    #define LCDRAM2H            *((volatile unsigned int *)(LCD_BASEADDR+0x28))
    #define LCDRAM3H            *((volatile unsigned int *)(LCD_BASEADDR+0x2C))
    #define LCDRAM4H            *((volatile unsigned int *)(LCD_BASEADDR+0x30))
    #define LCDRAM5H            *((volatile unsigned int *)(LCD_BASEADDR+0x34))
    #define LCDRAM6H            *((volatile unsigned int *)(LCD_BASEADDR+0x38))
    #define LCDRAM7H            *((volatile unsigned int *)(LCD_BASEADDR+0x3C))
    #define LCDCR               *((volatile unsigned int *)(LCD_BASEADDR+0x40))


#define UART_4_BASEADDR       (0x40010000)
		#define UART_4_RBR          *((volatile unsigned char *)(UART_4_BASEADDR+0x00))
		#define UART_4_THR          *((volatile unsigned char *)(UART_4_BASEADDR+0x00))
		#define UART_4_DLL          *((volatile unsigned char *)(UART_4_BASEADDR+0x00))
		#define UART_4_DLH          *((volatile unsigned char *)(UART_4_BASEADDR+0x04))
		#define UART_4_IER          *((volatile unsigned char *)(UART_4_BASEADDR+0x04))
		#define UART_4_IIR          *((volatile unsigned char *)(UART_4_BASEADDR+0x08))
		#define UART_4_FCR          *((volatile unsigned char *)(UART_4_BASEADDR+0x08))
		#define UART_4_LCR          *((volatile unsigned char *)(UART_4_BASEADDR+0x0c))			
		#define UART_4_LSR          *((volatile unsigned char *)(UART_4_BASEADDR+0x14))	

#define UART_5_BASEADDR       (0x40010400)
		#define UART_5_RBR          *((volatile unsigned char *)(UART_5_BASEADDR+0x00))
		#define UART_5_THR          *((volatile unsigned char *)(UART_5_BASEADDR+0x00))
		#define UART_5_DLL          *((volatile unsigned char *)(UART_5_BASEADDR+0x00))
		#define UART_5_DLH          *((volatile unsigned char *)(UART_5_BASEADDR+0x04))
		#define UART_5_IER          *((volatile unsigned char *)(UART_5_BASEADDR+0x04))
		#define UART_5_IIR          *((volatile unsigned char *)(UART_5_BASEADDR+0x08))
		#define UART_5_FCR          *((volatile unsigned char *)(UART_5_BASEADDR+0x08))
		#define UART_5_LCR          *((volatile unsigned char *)(UART_5_BASEADDR+0x0c))			
		#define UART_5_LSR          *((volatile unsigned char *)(UART_5_BASEADDR+0x14))

#define UART_6_BASEADDR       (0x40010800)
		#define UART_6_RBR          *((volatile unsigned char *)(UART_6_BASEADDR+0x00))
		#define UART_6_THR          *((volatile unsigned char *)(UART_6_BASEADDR+0x00))
		#define UART_6_DLL          *((volatile unsigned char *)(UART_6_BASEADDR+0x00))
		#define UART_6_DLH          *((volatile unsigned char *)(UART_6_BASEADDR+0x04))
		#define UART_6_IER          *((volatile unsigned char *)(UART_6_BASEADDR+0x04))
		#define UART_6_IIR          *((volatile unsigned char *)(UART_6_BASEADDR+0x08))
		#define UART_6_FCR          *((volatile unsigned char *)(UART_6_BASEADDR+0x08))
		#define UART_6_LCR          *((volatile unsigned char *)(UART_6_BASEADDR+0x0c))			
		#define UART_6_LSR          *((volatile unsigned char *)(UART_6_BASEADDR+0x14))

#define I2C_2_BASEADDR           (0x40010c00)
		#define I2C_2_CON            *((volatile unsigned int *)(I2C_2_BASEADDR+0x00))
		#define I2C_2_TAR            *((volatile unsigned int *)(I2C_2_BASEADDR+0x04))
		#define I2C_2_SAR            *((volatile unsigned int *)(I2C_2_BASEADDR+0x08))
		#define I2C_2_HS_MADDR       *((volatile unsigned int *)(I2C_2_BASEADDR+0x0c))
		#define I2C_2_DATA_CMD       *((volatile unsigned int *)(I2C_2_BASEADDR+0x10))
		#define I2C_2_SS_SCL_HCNT    *((volatile unsigned int *)(I2C_2_BASEADDR+0x14))
		#define I2C_2_SS_SCL_LCNT    *((volatile unsigned int *)(I2C_2_BASEADDR+0x18)) 
		#define I2C_2_FS_SCL_HCNT    *((volatile unsigned int *)(I2C_2_BASEADDR+0x1c))
		#define I2C_2_FS_SCL_LCNT    *((volatile unsigned int *)(I2C_2_BASEADDR+0x20))
		#define I2C_2_HS_SCL_HCNT    *((volatile unsigned int *)(I2C_2_BASEADDR+0x24))
		#define I2C_2_HS_SCL_LCNT    *((volatile unsigned int *)(I2C_2_BASEADDR+0x28))
		#define I2C_2_INTR_STAT      *((volatile unsigned int *)(I2C_2_BASEADDR+0x2c))
		#define I2C_2_INTR_MASK      *((volatile unsigned int *)(I2C_2_BASEADDR+0x30))
		#define I2C_2_RAW_INTR_STAT  *((volatile unsigned int *)(I2C_2_BASEADDR+0x34))
		#define I2C_2_RX_TL          *((volatile unsigned int *)(I2C_2_BASEADDR+0x38))
		#define I2C_2_TX_TL          *((volatile unsigned int *)(I2C_2_BASEADDR+0x3c))
		#define I2C_2_CLR_INTR       *((volatile unsigned int *)(I2C_2_BASEADDR+0x40))
		#define I2C_2_ENABLE         *((volatile unsigned int *)(I2C_2_BASEADDR+0x6c))
		#define I2C_2_STATUS         *((volatile unsigned int *)(I2C_2_BASEADDR+0x70))
		#define I2C_2_TXFLR          *((volatile unsigned int *)(I2C_2_BASEADDR+0x74))
		#define I2C_2_RXFLR          *((volatile unsigned int *)(I2C_2_BASEADDR+0x78))
		#define I2C_2_SDA_HOLD       *((volatile unsigned int *)(I2C_2_BASEADDR+0x7c))
		#define I2C_2_TX_ABRT_SOURCE *((volatile unsigned int *)(I2C_2_BASEADDR+0x80))
		#define I2C_2_DMA_CR         *((volatile unsigned int *)(I2C_2_BASEADDR+0x88))
		#define I2C_2_DMA_TDLR       *((volatile unsigned int *)(I2C_2_BASEADDR+0x8c))
		#define I2C_2_DMA_RDLR       *((volatile unsigned int *)(I2C_2_BASEADDR+0x90))

#define SSIM_3_BASEADDR       (0x40011000)
		#define SSIM_3_CTRLR0       *((volatile unsigned int *)(SSIM_3_BASEADDR+0x00))
		#define SSIM_3_CTRLR1       *((volatile unsigned int *)(SSIM_3_BASEADDR+0x04))
		#define SSIM_3_SSIENR       *((volatile unsigned int *)(SSIM_3_BASEADDR+0x08))
		#define SSIM_3_SER          *((volatile unsigned int *)(SSIM_3_BASEADDR+0x10))
		#define SSIM_3_BAUDR        *((volatile unsigned int *)(SSIM_3_BASEADDR+0x14))
		#define SSIM_3_TXFTLR       *((volatile unsigned int *)(SSIM_3_BASEADDR+0x18))
		#define SSIM_3_RXFTLR       *((volatile unsigned int *)(SSIM_3_BASEADDR+0x1c))
		#define SSIM_3_TXFLR        *((volatile unsigned int *)(SSIM_3_BASEADDR+0x20))
		#define SSIM_3_RXFLR        *((volatile unsigned int *)(SSIM_3_BASEADDR+0x24))
		#define SSIM_3_SR           *((volatile unsigned int *)(SSIM_3_BASEADDR+0x28))
		#define SSIM_3_IMR          *((volatile unsigned int *)(SSIM_3_BASEADDR+0x2c))
		#define SSIM_3_ISR          *((volatile unsigned int *)(SSIM_3_BASEADDR+0x30))
		#define SSIM_3_RISR         *((volatile unsigned int *)(SSIM_3_BASEADDR+0x34))
		#define SSIM_3_ICR          *((volatile unsigned int *)(SSIM_3_BASEADDR+0x48))
		#define SSIM_3_DMACR        *((volatile unsigned int *)(SSIM_3_BASEADDR+0x4c))
		#define SSIM_3_DMATDLR      *((volatile unsigned int *)(SSIM_3_BASEADDR+0x50))
		#define SSIM_3_DMARDLR      *((volatile unsigned int *)(SSIM_3_BASEADDR+0x54))
		#define SSIM_3_DR           *((volatile unsigned int *)(SSIM_3_BASEADDR+0x60))	

#define SSIM_4_BASEADDR       (0x40011400)
		#define SSIM_4_CTRLR0       *((volatile unsigned int *)(SSIM_4_BASEADDR+0x00))
		#define SSIM_4_CTRLR1       *((volatile unsigned int *)(SSIM_4_BASEADDR+0x04))
		#define SSIM_4_SSIENR       *((volatile unsigned int *)(SSIM_4_BASEADDR+0x08))
		#define SSIM_4_SER          *((volatile unsigned int *)(SSIM_4_BASEADDR+0x10))
		#define SSIM_4_BAUDR        *((volatile unsigned int *)(SSIM_4_BASEADDR+0x14))
		#define SSIM_4_TXFTLR       *((volatile unsigned int *)(SSIM_4_BASEADDR+0x18))
		#define SSIM_4_RXFTLR       *((volatile unsigned int *)(SSIM_4_BASEADDR+0x1c))
		#define SSIM_4_TXFLR        *((volatile unsigned int *)(SSIM_4_BASEADDR+0x20))
		#define SSIM_4_RXFLR        *((volatile unsigned int *)(SSIM_4_BASEADDR+0x24))
		#define SSIM_4_SR           *((volatile unsigned int *)(SSIM_4_BASEADDR+0x28))
		#define SSIM_4_IMR          *((volatile unsigned int *)(SSIM_4_BASEADDR+0x2c))
		#define SSIM_4_ISR          *((volatile unsigned int *)(SSIM_4_BASEADDR+0x30))
		#define SSIM_4_RISR         *((volatile unsigned int *)(SSIM_4_BASEADDR+0x34))
		#define SSIM_4_ICR          *((volatile unsigned int *)(SSIM_4_BASEADDR+0x48))
		#define SSIM_4_DMACR        *((volatile unsigned int *)(SSIM_4_BASEADDR+0x4c))
		#define SSIM_4_DMATDLR      *((volatile unsigned int *)(SSIM_4_BASEADDR+0x50))
		#define SSIM_4_DMARDLR      *((volatile unsigned int *)(SSIM_4_BASEADDR+0x54))
		#define SSIM_4_DR           *((volatile unsigned int *)(SSIM_4_BASEADDR+0x60))	

#define SSIS_3_BASEADDR       (0x40011800)
		#define SSIS_3_CTRLR0       *((volatile unsigned int *)(SSIS_3_BASEADDR+0x00))
		#define SSIS_3_CTRLR1       *((volatile unsigned int *)(SSIS_3_BASEADDR+0x04))
		#define SSIS_3_SSIENR       *((volatile unsigned int *)(SSIS_3_BASEADDR+0x08))
		#define SSIS_3_SER          *((volatile unsigned int *)(SSIS_3_BASEADDR+0x10))
		#define SSIS_3_BAUDR        *((volatile unsigned int *)(SSIS_3_BASEADDR+0x14))
		#define SSIS_3_TXFTLR       *((volatile unsigned int *)(SSIS_3_BASEADDR+0x18))
		#define SSIS_3_RXFTLR       *((volatile unsigned int *)(SSIS_3_BASEADDR+0x1c))
		#define SSIS_3_TXFLR        *((volatile unsigned int *)(SSIS_3_BASEADDR+0x20))
		#define SSIS_3_RXFLR        *((volatile unsigned int *)(SSIS_3_BASEADDR+0x24))
		#define SSIS_3_SR           *((volatile unsigned int *)(SSIS_3_BASEADDR+0x28))
		#define SSIS_3_IMR          *((volatile unsigned int *)(SSIS_3_BASEADDR+0x2c))
		#define SSIS_3_ISR          *((volatile unsigned int *)(SSIS_3_BASEADDR+0x30))
		#define SSIS_3_RISR         *((volatile unsigned int *)(SSIS_3_BASEADDR+0x34))
		#define SSIS_3_ICR          *((volatile unsigned int *)(SSIS_3_BASEADDR+0x48))
		#define SSIS_3_DMACR        *((volatile unsigned int *)(SSIS_3_BASEADDR+0x4c))
		#define SSIS_3_DMATDLR      *((volatile unsigned int *)(SSIS_3_BASEADDR+0x50))
		#define SSIS_3_DMARDLR      *((volatile unsigned int *)(SSIS_3_BASEADDR+0x54))
		#define SSIS_3_DR           *((volatile unsigned int *)(SSIS_3_BASEADDR+0x60))

#define SSIS_4_BASEADDR       (0x40011c00)
		#define SSIS_4_CTRLR0       *((volatile unsigned int *)(SSIS_4_BASEADDR+0x00))
		#define SSIS_4_CTRLR1       *((volatile unsigned int *)(SSIS_4_BASEADDR+0x04))
		#define SSIS_4_SSIENR       *((volatile unsigned int *)(SSIS_4_BASEADDR+0x08))
		#define SSIS_4_SER          *((volatile unsigned int *)(SSIS_4_BASEADDR+0x10))
		#define SSIS_4_BAUDR        *((volatile unsigned int *)(SSIS_4_BASEADDR+0x14))
		#define SSIS_4_TXFTLR       *((volatile unsigned int *)(SSIS_4_BASEADDR+0x18))
		#define SSIS_4_RXFTLR       *((volatile unsigned int *)(SSIS_4_BASEADDR+0x1c))
		#define SSIS_4_TXFLR        *((volatile unsigned int *)(SSIS_4_BASEADDR+0x20))
		#define SSIS_4_RXFLR        *((volatile unsigned int *)(SSIS_4_BASEADDR+0x24))
		#define SSIS_4_SR           *((volatile unsigned int *)(SSIS_4_BASEADDR+0x28))
		#define SSIS_4_IMR          *((volatile unsigned int *)(SSIS_4_BASEADDR+0x2c))
		#define SSIS_4_ISR          *((volatile unsigned int *)(SSIS_4_BASEADDR+0x30))
		#define SSIS_4_RISR         *((volatile unsigned int *)(SSIS_4_BASEADDR+0x34))
		#define SSIS_4_ICR          *((volatile unsigned int *)(SSIS_4_BASEADDR+0x48))
		#define SSIS_4_DMACR        *((volatile unsigned int *)(SSIS_4_BASEADDR+0x4c))
		#define SSIS_4_DMATDLR      *((volatile unsigned int *)(SSIS_4_BASEADDR+0x50))
		#define SSIS_4_DMARDLR      *((volatile unsigned int *)(SSIS_4_BASEADDR+0x54))
		#define SSIS_4_DR           *((volatile unsigned int *)(SSIS_4_BASEADDR+0x60))

#define RTC_BASEADDR          (0x40012000)
		#define SIXTEENOFS        *((volatile unsigned char *)(RTC_BASEADDR+0x00))
		#define SECOND            *((volatile unsigned char *)(RTC_BASEADDR+0x04)) 
		#define MINUTE            *((volatile unsigned char *)(RTC_BASEADDR+0x08)) 
		#define HOUR              *((volatile unsigned char *)(RTC_BASEADDR+0x0c)) 
		#define DAY               *((volatile unsigned char *)(RTC_BASEADDR+0x10)) 
		#define MONTH             *((volatile unsigned char *)(RTC_BASEADDR+0x14)) 
		#define YEAR0             *((volatile unsigned char *)(RTC_BASEADDR+0x18)) 
		#define YEAR1             *((volatile unsigned char *)(RTC_BASEADDR+0x1c)) 
		#define SIXTEENOFS_DIS    *((volatile unsigned char *)(RTC_BASEADDR+0x20)) 
		#define SECOND_DIS        *((volatile unsigned char *)(RTC_BASEADDR+0x24))
		#define MINUTE_DIS        *((volatile unsigned char *)(RTC_BASEADDR+0x28)) 
		#define HOUR_DIS          *((volatile unsigned char *)(RTC_BASEADDR+0x2c))			
		#define DAY_DIS           *((volatile unsigned char *)(RTC_BASEADDR+0x30))
    #define MONTH_DIS         *((volatile unsigned char *)(RTC_BASEADDR+0x34))
    #define YEAR0_DIS         *((volatile unsigned char *)(RTC_BASEADDR+0x38))
    #define YEAR1_DIS         *((volatile unsigned char *)(RTC_BASEADDR+0x3c)) 			
		#define ADJUST_INC        *((volatile unsigned char *)(RTC_BASEADDR+0x40)) 
		#define ADJUST_DEC        *((volatile unsigned char *)(RTC_BASEADDR+0x44)) 
		#define FORMAT            *((volatile unsigned char *)(RTC_BASEADDR+0x48)) 
		#define INTERVAL          *((volatile unsigned char *)(RTC_BASEADDR+0x4c))
		#define CONFIG0           *((volatile unsigned char *)(RTC_BASEADDR+0x58))
		#define CONFIG1           *((volatile unsigned char *)(RTC_BASEADDR+0x5c))
		#define PHASE             *((volatile unsigned char *)(RTC_BASEADDR+0x60))
		#define HOLD              *((volatile unsigned char *)(RTC_BASEADDR+0x64))
		#define INTERRUPT         *((volatile unsigned char *)(RTC_BASEADDR+0x6c))	
						

#define WDT_BASEADDR          (0x40012400)
    #define WDT_CR            *((volatile unsigned char *)(WDT_BASEADDR+0x00)) 
		#define WDT_TORR          *((volatile unsigned char *)(WDT_BASEADDR+0x04)) 
		#define WDT_CRR           *((volatile unsigned char *)(WDT_BASEADDR+0x0c))
		#define WDT_EOI           *((volatile unsigned char *)(WDT_BASEADDR+0x14))

#define BASE_TIMER_BASEADDR   (0x40012800)
		#define BTIMER_LOAD_COUNT  *((volatile unsigned int  *)(BASE_TIMER_BASEADDR+0x00))
		#define BTIMER_CURVAL      *((volatile unsigned char *)(BASE_TIMER_BASEADDR+0x04))
		#define BTIMER_CTRL        *((volatile unsigned char *)(BASE_TIMER_BASEADDR+0x08))
		#define BTIMER_EOI         *((volatile unsigned int  *)(BASE_TIMER_BASEADDR+0x0c))
		#define BTIMERS_INT_STAT   *((volatile unsigned int  *)(BASE_TIMER_BASEADDR+0xa0))
		#define BTIMERS_EOI        *((volatile unsigned int  *)(BASE_TIMER_BASEADDR+0xa4))
		#define BTIMER_LOAD_COUNT2 *((volatile unsigned int  *)(BASE_TIMER_BASEADDR+0xb0))
		
		#define BTIMER_GATE        *((volatile unsigned int  *)(BASE_TIMER_BASEADDR+0xd0))

#define GPIO_BASEADDR         (0x40012c00)
		#define P0                 *((volatile unsigned int *)(GPIO_BASEADDR+0x00))
		#define P0_DIR             *((volatile unsigned int *)(GPIO_BASEADDR+0x04))
		#define P0_PULSE_SEL       *((volatile unsigned int *)(GPIO_BASEADDR+0x08))
		#define P0_EDGE_SEL        *((volatile unsigned int *)(GPIO_BASEADDR+0x0c))
		#define P0_IE              *((volatile unsigned int *)(GPIO_BASEADDR+0x10))
		#define P0_IFG             *((volatile unsigned int *)(GPIO_BASEADDR+0x14))
		#define P0_PH              *((volatile unsigned int *)(GPIO_BASEADDR+0x18))
		#define P0_DS              *((volatile unsigned int *)(GPIO_BASEADDR+0x1c))
		#define P0_OPENDRAIN       *((volatile unsigned int *)(GPIO_BASEADDR+0x20))
		#define P0_SEL0            *((volatile unsigned int *)(GPIO_BASEADDR+0x24))
		#define P0_SEL1            *((volatile unsigned int *)(GPIO_BASEADDR+0x28))
		#define P0_SEL2            *((volatile unsigned int *)(GPIO_BASEADDR+0x2c))
		
		#define P1                 *((volatile unsigned int *)(GPIO_BASEADDR+0x40))
		#define P1_DIR             *((volatile unsigned int *)(GPIO_BASEADDR+0x44))
		#define P1_PULSE_SEL       *((volatile unsigned int *)(GPIO_BASEADDR+0x48))
		#define P1_EDGE_SEL        *((volatile unsigned int *)(GPIO_BASEADDR+0x4c))
		#define P1_IE              *((volatile unsigned int *)(GPIO_BASEADDR+0x50))
		#define P1_IFG             *((volatile unsigned int *)(GPIO_BASEADDR+0x54))
		#define P1_PH              *((volatile unsigned int *)(GPIO_BASEADDR+0x58))
		#define P1_DS              *((volatile unsigned int *)(GPIO_BASEADDR+0x5c))
		#define P1_OPENDRAIN       *((volatile unsigned int *)(GPIO_BASEADDR+0x60))
		#define P1_SEL0            *((volatile unsigned int *)(GPIO_BASEADDR+0x64))
		#define P1_SEL1            *((volatile unsigned int *)(GPIO_BASEADDR+0x68))
		#define P1_SEL2            *((volatile unsigned int *)(GPIO_BASEADDR+0x6c))
			
		#define P2                 *((volatile unsigned int *)(GPIO_BASEADDR+0x80))
		#define P2_DIR             *((volatile unsigned int *)(GPIO_BASEADDR+0x84))
		#define P2_PULSE_SEL       *((volatile unsigned int *)(GPIO_BASEADDR+0x88))
		#define P2_EDGE_SEL        *((volatile unsigned int *)(GPIO_BASEADDR+0x8c))
		#define P2_IE              *((volatile unsigned int *)(GPIO_BASEADDR+0x90))
		#define P2_IFG             *((volatile unsigned int *)(GPIO_BASEADDR+0x94))
		#define P2_PH              *((volatile unsigned int *)(GPIO_BASEADDR+0x98))
		#define P2_DS              *((volatile unsigned int *)(GPIO_BASEADDR+0x9c))
		#define P2_OPENDRAIN       *((volatile unsigned int *)(GPIO_BASEADDR+0xa0))
		#define P2_SEL0            *((volatile unsigned int *)(GPIO_BASEADDR+0xa4))
		#define P2_SEL1            *((volatile unsigned int *)(GPIO_BASEADDR+0xa8))
		#define P2_SEL2            *((volatile unsigned int *)(GPIO_BASEADDR+0xac))
			
		#define P3                 *((volatile unsigned int *)(GPIO_BASEADDR+0xc0))
		#define P3_DIR             *((volatile unsigned int *)(GPIO_BASEADDR+0xc4))
		#define P3_PULSE_SEL       *((volatile unsigned int *)(GPIO_BASEADDR+0xc8))
		#define P3_EDGE_SEL        *((volatile unsigned int *)(GPIO_BASEADDR+0xcc))
		#define P3_IE              *((volatile unsigned int *)(GPIO_BASEADDR+0xd0))
		#define P3_IFG             *((volatile unsigned int *)(GPIO_BASEADDR+0xd4))
		#define P3_PH              *((volatile unsigned int *)(GPIO_BASEADDR+0xd8))
		#define P3_DS              *((volatile unsigned int *)(GPIO_BASEADDR+0xdc))
		#define P3_OPENDRAIN       *((volatile unsigned int *)(GPIO_BASEADDR+0xe0))
		#define P3_SEL0            *((volatile unsigned int *)(GPIO_BASEADDR+0xe4))
		#define P3_SEL1            *((volatile unsigned int *)(GPIO_BASEADDR+0xe8))
		#define P3_SEL2            *((volatile unsigned int *)(GPIO_BASEADDR+0xec))
			
		#define P4                 *((volatile unsigned int *)(GPIO_BASEADDR+0x100))
		#define P4_DIR             *((volatile unsigned int *)(GPIO_BASEADDR+0x104))
		#define P4_PULSE_SEL       *((volatile unsigned int *)(GPIO_BASEADDR+0x108))
		#define P4_EDGE_SEL        *((volatile unsigned int *)(GPIO_BASEADDR+0x10c))
		#define P4_IE              *((volatile unsigned int *)(GPIO_BASEADDR+0x110))
		#define P4_IFG             *((volatile unsigned int *)(GPIO_BASEADDR+0x114))
		#define P4_PH              *((volatile unsigned int *)(GPIO_BASEADDR+0x118))
		#define P4_DS              *((volatile unsigned int *)(GPIO_BASEADDR+0x11c))
		#define P4_OPENDRAIN       *((volatile unsigned int *)(GPIO_BASEADDR+0x120))
		#define P4_SEL0            *((volatile unsigned int *)(GPIO_BASEADDR+0x124))
		#define P4_SEL1            *((volatile unsigned int *)(GPIO_BASEADDR+0x128))
		#define P4_SEL2            *((volatile unsigned int *)(GPIO_BASEADDR+0x12c))
			
		#define P5                 *((volatile unsigned int *)(GPIO_BASEADDR+0x140))
		#define P5_DIR             *((volatile unsigned int *)(GPIO_BASEADDR+0x144))
		#define P5_PULSE_SEL       *((volatile unsigned int *)(GPIO_BASEADDR+0x148))
		#define P5_EDGE_SEL        *((volatile unsigned int *)(GPIO_BASEADDR+0x14c))
		#define P5_IE              *((volatile unsigned int *)(GPIO_BASEADDR+0x150))
		#define P5_IFG             *((volatile unsigned int *)(GPIO_BASEADDR+0x154))
		#define P5_PH              *((volatile unsigned int *)(GPIO_BASEADDR+0x158))
		#define P5_DS              *((volatile unsigned int *)(GPIO_BASEADDR+0x15c))
		#define P5_OPENDRAIN       *((volatile unsigned int *)(GPIO_BASEADDR+0x160))
		#define P5_SEL0            *((volatile unsigned int *)(GPIO_BASEADDR+0x164))
		#define P5_SEL1            *((volatile unsigned int *)(GPIO_BASEADDR+0x168))
		#define P5_SEL2            *((volatile unsigned int *)(GPIO_BASEADDR+0x16c))	

    #define P6                 *((volatile unsigned int *)(GPIO_BASEADDR+0x180))
		#define P6_DIR             *((volatile unsigned int *)(GPIO_BASEADDR+0x184))
		#define P6_PULSE_SEL       *((volatile unsigned int *)(GPIO_BASEADDR+0x188))
		#define P6_EDGE_SEL        *((volatile unsigned int *)(GPIO_BASEADDR+0x18c))
		#define P6_IE              *((volatile unsigned int *)(GPIO_BASEADDR+0x190))
		#define P6_IFG             *((volatile unsigned int *)(GPIO_BASEADDR+0x194))
		#define P6_PH              *((volatile unsigned int *)(GPIO_BASEADDR+0x198))
		#define P6_DS              *((volatile unsigned int *)(GPIO_BASEADDR+0x19c))
		#define P6_OPENDRAIN       *((volatile unsigned int *)(GPIO_BASEADDR+0x1a0))
		#define P6_SEL0            *((volatile unsigned int *)(GPIO_BASEADDR+0x1a4))
		#define P6_SEL1            *((volatile unsigned int *)(GPIO_BASEADDR+0x1a8))
		#define P6_SEL2            *((volatile unsigned int *)(GPIO_BASEADDR+0x1ac))

#define PCA_BASEADDR          (0x40013000)
		#define PCA1_CCON         *((volatile unsigned int  *)(PCA_BASEADDR+0x00))
		#define PCA1_CMOD         *((volatile unsigned int  *)(PCA_BASEADDR+0x04))
		#define PCA1_CH           *((volatile unsigned int  *)(PCA_BASEADDR+0x08))
		#define PCA1_CL           *((volatile unsigned int  *)(PCA_BASEADDR+0x0c))
		#define PCA1_CCAPM0       *((volatile unsigned int  *)(PCA_BASEADDR+0x010))
		#define PCA1_CCAPM1       *((volatile unsigned int  *)(PCA_BASEADDR+0x014))
		#define PCA1_CCAPM2       *((volatile unsigned int  *)(PCA_BASEADDR+0x018))
		#define PCA1_CCAPM3       *((volatile unsigned int  *)(PCA_BASEADDR+0x01c))
		#define PCA1_CCAPM4       *((volatile unsigned int  *)(PCA_BASEADDR+0x020))
		#define PCA1_CCAP0H       *((volatile unsigned int  *)(PCA_BASEADDR+0x024))
		#define PCA1_CCAP0L       *((volatile unsigned int  *)(PCA_BASEADDR+0x028))
		#define PCA1_CCAP1H       *((volatile unsigned int  *)(PCA_BASEADDR+0x02c))
		#define PCA1_CCAP1L       *((volatile unsigned int  *)(PCA_BASEADDR+0x030))
		#define PCA1_CCAP2H       *((volatile unsigned int  *)(PCA_BASEADDR+0x034))
		#define PCA1_CCAP2L       *((volatile unsigned int  *)(PCA_BASEADDR+0x038))
		#define PCA1_CCAP3H       *((volatile unsigned int  *)(PCA_BASEADDR+0x03c))
		#define PCA1_CCAP3L       *((volatile unsigned int  *)(PCA_BASEADDR+0x040))
		#define PCA1_CCAP4H       *((volatile unsigned int  *)(PCA_BASEADDR+0x044))
		#define PCA1_CCAP4L       *((volatile unsigned int  *)(PCA_BASEADDR+0x048))
		#define PCA1_CCAPO        *((volatile unsigned int  *)(PCA_BASEADDR+0x04c))
			
	  #define PCA2_CCON         *((volatile unsigned int  *)(PCA_BASEADDR+0x50))
		#define PCA2_CMOD         *((volatile unsigned int  *)(PCA_BASEADDR+0x54))
		#define PCA2_CH           *((volatile unsigned int  *)(PCA_BASEADDR+0x58))
		#define PCA2_CL           *((volatile unsigned int  *)(PCA_BASEADDR+0x5c))
		#define PCA2_CCAPM0       *((volatile unsigned int  *)(PCA_BASEADDR+0x60))
		#define PCA2_CCAPM1       *((volatile unsigned int  *)(PCA_BASEADDR+0x64))
		#define PCA2_CCAPM2       *((volatile unsigned int  *)(PCA_BASEADDR+0x68))
		#define PCA2_CCAPM3       *((volatile unsigned int  *)(PCA_BASEADDR+0x6c))
		#define PCA2_CCAPM4       *((volatile unsigned int  *)(PCA_BASEADDR+0x70))
		#define PCA2_CCAP0H       *((volatile unsigned int  *)(PCA_BASEADDR+0x74))
		#define PCA2_CCAP0L       *((volatile unsigned int  *)(PCA_BASEADDR+0x78))
		#define PCA2_CCAP1H       *((volatile unsigned int  *)(PCA_BASEADDR+0x7c))
		#define PCA2_CCAP1L       *((volatile unsigned int  *)(PCA_BASEADDR+0x80))
		#define PCA2_CCAP2H       *((volatile unsigned int  *)(PCA_BASEADDR+0x84))
		#define PCA2_CCAP2L       *((volatile unsigned int  *)(PCA_BASEADDR+0x88))
		#define PCA2_CCAP3H       *((volatile unsigned int  *)(PCA_BASEADDR+0x8c))
		#define PCA2_CCAP3L       *((volatile unsigned int  *)(PCA_BASEADDR+0x90))
		#define PCA2_CCAP4H       *((volatile unsigned int  *)(PCA_BASEADDR+0x94))
		#define PCA2_CCAP4L       *((volatile unsigned int  *)(PCA_BASEADDR+0x98))
		#define PCA2_CCAPO        *((volatile unsigned int  *)(PCA_BASEADDR+0x9c))
			
		#define PCA3_CCON         *((volatile unsigned int  *)(PCA_BASEADDR+0xa0))
		#define PCA3_CMOD         *((volatile unsigned int  *)(PCA_BASEADDR+0xa4))
		#define PCA3_CH           *((volatile unsigned int  *)(PCA_BASEADDR+0xa8))
		#define PCA3_CL           *((volatile unsigned int  *)(PCA_BASEADDR+0xac))
		#define PCA3_CCAPM0       *((volatile unsigned int  *)(PCA_BASEADDR+0xb0))
		#define PCA3_CCAPM1       *((volatile unsigned int  *)(PCA_BASEADDR+0xb4))
		#define PCA3_CCAPM2       *((volatile unsigned int  *)(PCA_BASEADDR+0xb8))
		#define PCA3_CCAPM3       *((volatile unsigned int  *)(PCA_BASEADDR+0xbc))
		#define PCA3_CCAPM4       *((volatile unsigned int  *)(PCA_BASEADDR+0xc0))
		#define PCA3_CCAP0H       *((volatile unsigned int  *)(PCA_BASEADDR+0xc4))
		#define PCA3_CCAP0L       *((volatile unsigned int  *)(PCA_BASEADDR+0xc8))
		#define PCA3_CCAP1H       *((volatile unsigned int  *)(PCA_BASEADDR+0xcc))
		#define PCA3_CCAP1L       *((volatile unsigned int  *)(PCA_BASEADDR+0xd0))
		#define PCA3_CCAP2H       *((volatile unsigned int  *)(PCA_BASEADDR+0xd4))
		#define PCA3_CCAP2L       *((volatile unsigned int  *)(PCA_BASEADDR+0xd8))
		#define PCA3_CCAP3H       *((volatile unsigned int  *)(PCA_BASEADDR+0xdc))
		#define PCA3_CCAP3L       *((volatile unsigned int  *)(PCA_BASEADDR+0xe0))
		#define PCA3_CCAP4H       *((volatile unsigned int  *)(PCA_BASEADDR+0xe4))
		#define PCA3_CCAP4L       *((volatile unsigned int  *)(PCA_BASEADDR+0xe8))
		#define PCA3_CCAPO        *((volatile unsigned int  *)(PCA_BASEADDR+0xec))
			
		#define PCA4_CCON         *((volatile unsigned int  *)(PCA_BASEADDR+0xf0))
		#define PCA4_CMOD         *((volatile unsigned int  *)(PCA_BASEADDR+0xf4))
		#define PCA4_CH           *((volatile unsigned int  *)(PCA_BASEADDR+0xf8))
		#define PCA4_CL           *((volatile unsigned int  *)(PCA_BASEADDR+0xfc))
		#define PCA4_CCAPM0       *((volatile unsigned int  *)(PCA_BASEADDR+0x100))
		#define PCA4_CCAPM1       *((volatile unsigned int  *)(PCA_BASEADDR+0x104))
		#define PCA4_CCAPM2       *((volatile unsigned int  *)(PCA_BASEADDR+0x108))
		#define PCA4_CCAPM3       *((volatile unsigned int  *)(PCA_BASEADDR+0x10c))
		#define PCA4_CCAPM4       *((volatile unsigned int  *)(PCA_BASEADDR+0x110))
		#define PCA4_CCAP0H       *((volatile unsigned int  *)(PCA_BASEADDR+0x114))
		#define PCA4_CCAP0L       *((volatile unsigned int  *)(PCA_BASEADDR+0x118))
		#define PCA4_CCAP1H       *((volatile unsigned int  *)(PCA_BASEADDR+0x11c))
		#define PCA4_CCAP1L       *((volatile unsigned int  *)(PCA_BASEADDR+0x120))
		#define PCA4_CCAP2H       *((volatile unsigned int  *)(PCA_BASEADDR+0x124))
		#define PCA4_CCAP2L       *((volatile unsigned int  *)(PCA_BASEADDR+0x128))
		#define PCA4_CCAP3H       *((volatile unsigned int  *)(PCA_BASEADDR+0x12c))
		#define PCA4_CCAP3L       *((volatile unsigned int  *)(PCA_BASEADDR+0x130))
		#define PCA4_CCAP4H       *((volatile unsigned int  *)(PCA_BASEADDR+0x134))
		#define PCA4_CCAP4L       *((volatile unsigned int  *)(PCA_BASEADDR+0x138))
		#define PCA4_CCAPO        *((volatile unsigned int  *)(PCA_BASEADDR+0x13c))
			

#define SYS_CTRL_BASEADDR  (0x40013400)
		#define SYS_CLK0          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x00))
		#define SYS_CLK1          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x04))
		#define PMU_CTRL          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x08))
		#define IRC16M_SFR        *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x0c))
		#define X32M_SFR          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x10))		
		#define IRC32K_SFR        *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x14))
		#define X32K_SFR          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x18))
		#define RESET_FLAG        *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x20))
    #define BGR_CTRL          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x28))
    #define LVD_CTRL0         *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x2c))
    #define LVD_CTRL1         *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x30))
    #define VC_CTRL0          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x34))
    #define VC_CTRL1          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x38))
    #define PERI_CLK_CTRL0    *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x40))
    #define PERI_CLK_CTRL1    *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x44))
    #define PERI_RST_CTRL0    *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x48))
    #define PERI_RST_CTRL1    *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x4c))
    #define CLK_CTRIM_CTRL    *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x50))
    #define CLK_CALIBRATION   *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x58))
		#define LPUART            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x5c))				
    #define ADC_CTRL0         *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x60))
    #define ADC_CTRL1         *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x64))
    #define ADC_CTRL2         *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x68))
    #define ADC_RESULT_ACC    *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x6c))
    #define DEBUG_ACTIVE      *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x70))
    #define BUZZER_SFR        *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x74))
    #define TICK_TIMER        *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x7c))                   
    #define ADC_RESULT0       *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x80))
    #define ADC_RESULT1       *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x84))                           
    #define ADC_RESULT2       *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x88))
    #define ADC_RESULT3       *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x8c))
    #define ADC_RESULT4       *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x90))        
    #define ADC_RESULT5       *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x94))
    #define ADC_RESULT6       *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x98))
    #define ADC_RESULT7       *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x9c))
    #define BKRAM0            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xc0))        
    #define BKRAM1            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xc4))                  
    #define BKRAM2            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xc8))
    #define BKRAM3            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xcc))
    #define BKRAM4            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xd0))                 
    #define BKRAM5            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xd4))
    #define BKRAM6            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xd8))
    #define BKRAM7            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xdc))
    #define BKRAM8            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xe0))
    #define BKRAM9            *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xe4))
    #define BKRAM10           *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xe8))
    #define BKRAM11           *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xec))
    #define BKRAM12           *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xf0))
    #define BKRAM13           *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xf4))         
    #define BKRAM14           *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xf8))
    #define BKRAM15           *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0xfc))
    #define SFR_LOCK          *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x100))
    #define BOOT0             *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x104))
    #define BOOT1             *((volatile unsigned int  *)(SYS_CTRL_BASEADDR+0x108))		
		
#define EFLASH_CTRL_BASEADDR  (0x40020000)
		#define TNVS              *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x00))
		#define TPGS              *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x04))
		#define TPROG             *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x08))
		#define TNVH              *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x0c))
		#define TRCV              *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x10))
		#define TERASE            *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x14))
		#define TME               *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x18))
		#define TNVH1             *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x1c))			
		#define FLASH_CTRL        *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x20))
		#define FLASH_FLAG        *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x24))		
			
		#define PL_SEQ0           *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x30))
//		#define PL_SEQ1           *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x34))
		#define MAIN_PL0          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x38))
		#define MAIN_PL1          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x3c))
		#define MAIN_PL2          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x40))
		#define MAIN_PL3          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x44))
		#define MAIN_PL4          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x48))
		#define MAIN_PL5          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x4c))
		#define MAIN_PL6          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x50))
		#define MAIN_PL7          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x54))
		#define INFO_PL           *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x58))
				
		#define REMAP_SEL         *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x60))
		#define RAM_FLAG          *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x64))
		#define RAM_ERR           *((volatile unsigned int  *)(EFLASH_CTRL_BASEADDR+0x68))

#define DMAC_BASEADDR         (0x40020c00)
//channel 0 register		
    #define DMAC_SAR0           *((volatile unsigned int *)(DMAC_BASEADDR+0x000))	
		#define DMAC_DAR0           *((volatile unsigned int *)(DMAC_BASEADDR+0x008))
	  #define DMAC_LLP0           *((volatile unsigned int *)(DMAC_BASEADDR+0x010))
			
    #define DMAC_CTL0_L         *((volatile unsigned long*)(DMAC_BASEADDR+0x018))	
    #define DMAC_CTL0_H         *((volatile unsigned long*)(DMAC_BASEADDR+0x01c))			
		#define DMAC_CFG0_L         *((volatile unsigned long*)(DMAC_BASEADDR+0x040))
		#define DMAC_CFG0_H         *((volatile unsigned long*)(DMAC_BASEADDR+0x044))
			
		#define DMAC_DSTAT0_L       *((volatile unsigned long*)(DMAC_BASEADDR+0x028))
		#define DMAC_DSTAT0_H       *((volatile unsigned long*)(DMAC_BASEADDR+0x02c))
			
//channel 1 register		
    #define DMAC_SAR1           *((volatile unsigned int *)(DMAC_BASEADDR+0x058))	
		#define DMAC_DAR1           *((volatile unsigned int *)(DMAC_BASEADDR+0x060))
	  #define DMAC_LLP1           *((volatile unsigned int *)(DMAC_BASEADDR+0x068))
			
    #define DMAC_CTL1_L         *((volatile unsigned long*)(DMAC_BASEADDR+0x070))	
    #define DMAC_CTL1_H         *((volatile unsigned long*)(DMAC_BASEADDR+0x074))			
		#define DMAC_CFG1_L         *((volatile unsigned long*)(DMAC_BASEADDR+0x098))
		#define DMAC_CFG1_H         *((volatile unsigned long*)(DMAC_BASEADDR+0x09c))
		
		#define DMAC_DSTAT1_L       *((volatile unsigned long*)(DMAC_BASEADDR+0x080))
		#define DMAC_DSTAT1_H       *((volatile unsigned long*)(DMAC_BASEADDR+0x084))
			
		
//common register		
    #define DMAC_CFG            *((volatile unsigned long *)(DMAC_BASEADDR+0x398))	
    #define DMAC_CH_EN          *((volatile unsigned long *)(DMAC_BASEADDR+0x3a0))	

		#define DMAC_STATUS_BLK     *((volatile unsigned long *)(DMAC_BASEADDR+0x2f0))	
		
    #define DMAC_CLR_TFR     *((volatile unsigned long *)(DMAC_BASEADDR+0x338))	
    #define DMAC_CLR_BLK     *((volatile unsigned long *)(DMAC_BASEADDR+0x340))
    #define DMAC_CLR_SRCTRAN *((volatile unsigned long *)(DMAC_BASEADDR+0x348))
    #define DMAC_CLR_DSTTRAN *((volatile unsigned long *)(DMAC_BASEADDR+0x350))
    #define DMAC_CLR_ERR     *((volatile unsigned long *)(DMAC_BASEADDR+0x358))	
			
		#define DMAC_STATUS_INT  *((volatile unsigned long *)(DMAC_BASEADDR+0x360))	
			
		#define DMAC_MASK_BLK     *((volatile unsigned long *)(DMAC_BASEADDR+0x318))	
			
#define CRC_BASEADDR         (0x40021000)	
    #define CRC_CTRL          *((volatile unsigned int *)(CRC_BASEADDR+0x00))
    #define CRC_RESULT        *((volatile unsigned int *)(CRC_BASEADDR+0x04))
		#define CRC_RAND          *((volatile unsigned int *)(CRC_BASEADDR+0x08))	
		#define CRC_FLAG          *((volatile unsigned int *)(CRC_BASEADDR+0x0c))	
		#define CRC_DATA          *((volatile unsigned int *)(CRC_BASEADDR+0x80))	
    #define CRC_DATA16        *((volatile unsigned short *)(CRC_BASEADDR+0x80))			
			
#define DES_BASEADDR         (0x40021800)
		#define DES_CTRL          *((volatile unsigned int *)(DES_BASEADDR+0x00))
		#define DES_RAND          *((volatile unsigned int *)(DES_BASEADDR+0x0c))
		#define DES_IV_L          *((volatile unsigned int *)(DES_BASEADDR+0x18))
		#define DES_IV_H          *((volatile unsigned int *)(DES_BASEADDR+0x1c))
		#define DES_DATA_L        *((volatile unsigned int *)(DES_BASEADDR+0x20))
		#define DES_DATA_H        *((volatile unsigned int *)(DES_BASEADDR+0x24))
		#define DES_KEY1_L        *((volatile unsigned int *)(DES_BASEADDR+0x28))
		#define DES_KEY1_H        *((volatile unsigned int *)(DES_BASEADDR+0x2c))
		#define DES_KEY2_L        *((volatile unsigned int *)(DES_BASEADDR+0x30))
		#define DES_KEY2_H        *((volatile unsigned int *)(DES_BASEADDR+0x34))
		#define DES_KEY3_L        *((volatile unsigned int *)(DES_BASEADDR+0x38))
		#define DES_KEY3_H        *((volatile unsigned int *)(DES_BASEADDR+0x3c))
		
#define SM4_BASEADDR         (0x40022000)
		#define SM4_CTRL          *((volatile unsigned int *)(SM4_BASEADDR+0x00))
		#define SM4_RAND1         *((volatile unsigned int *)(SM4_BASEADDR+0x08))
		#define SM4_RAND2         *((volatile unsigned int *)(SM4_BASEADDR+0x0c))
		#define SM4_DATA1         *((volatile unsigned int *)(SM4_BASEADDR+0x10))
		#define SM4_DATA2         *((volatile unsigned int *)(SM4_BASEADDR+0x14))
		#define SM4_DATA3         *((volatile unsigned int *)(SM4_BASEADDR+0x18))
		#define SM4_DATA4         *((volatile unsigned int *)(SM4_BASEADDR+0x1c))
		#define SM4_MKEY1         *((volatile unsigned int *)(SM4_BASEADDR+0x20))
		#define SM4_MKEY2         *((volatile unsigned int *)(SM4_BASEADDR+0x24))
		#define SM4_MKEY3         *((volatile unsigned int *)(SM4_BASEADDR+0x28))
		#define SM4_MKEY4         *((volatile unsigned int *)(SM4_BASEADDR+0x2c))
		#define SM4_SKEY1         *((volatile unsigned int *)(SM4_BASEADDR+0x30))
		#define SM4_SKEY2         *((volatile unsigned int *)(SM4_BASEADDR+0x34))
		#define SM4_SKEY3         *((volatile unsigned int *)(SM4_BASEADDR+0x38))
		#define SM4_SKEY4         *((volatile unsigned int *)(SM4_BASEADDR+0x3c))
		
		

#define NVIC_BASEADDR      (0xe000e000)
    #define NVIC_ISER           *((volatile unsigned int *)(NVIC_BASEADDR+0x100)) 	
    #define NVIC_ICER           *((volatile unsigned int *)(NVIC_BASEADDR+0x180))
		#define NVIC_PSER           *((volatile unsigned int *)(NVIC_BASEADDR+0x200)) 	
    #define NVIC_PCER           *((volatile unsigned int *)(NVIC_BASEADDR+0x280))
		#define NVIC_IPR0           *((volatile unsigned int *)(NVIC_BASEADDR+0x400))
		#define NVIC_IPR1           *((volatile unsigned int *)(NVIC_BASEADDR+0x404))
		#define NVIC_IPR2           *((volatile unsigned int *)(NVIC_BASEADDR+0x408))
		#define NVIC_IPR3           *((volatile unsigned int *)(NVIC_BASEADDR+0x40c))
		#define NVIC_IPR4           *((volatile unsigned int *)(NVIC_BASEADDR+0x410))
		#define NVIC_IPR5           *((volatile unsigned int *)(NVIC_BASEADDR+0x414))
		#define NVIC_IPR6           *((volatile unsigned int *)(NVIC_BASEADDR+0x418))
		#define NVIC_IPR7           *((volatile unsigned int *)(NVIC_BASEADDR+0x41c))
			
			
		#define DEEPSLEEP           *((volatile unsigned int *)(0xe000ed10))
		

#endif
